services:
  postgres:
    container_name: postgres
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: pet_family
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - "5434:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
  seq:
    container_name: seq
    image: datalust/seq
    restart: always
    environment:
      - ACCEPT_EULA=Y
    ports:
      - "5433:80"
  minio:
    container_name: minio
    image: minio/minio
    restart: always
    environment:
      MINIO_ROOT_USER: root
      MINIO_ROOT_PASSWORD: rootroot
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio-data:/var/minio/data
    command: server --console-address ":9001" /var/minio/data

volumes:
  postgres-data:
  minio-data: